# Usar una imagen base ligera de Node.js
FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios desde la carpeta web
COPY ../../web/package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el código fuente al contenedor desde la carpeta web
COPY ../../web .

# Exponer el puerto 5173 para el frontend
EXPOSE 5173

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host"]