# Usa una imagen base oficial de Python
FROM python:3.10-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY ../../api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ../../api .

# Establece las variables de entorno
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# Expone el puerto del backend
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["flask", "run", "--host=0.0.0.0"]