# Usar una oficial de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY ../../api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ../../api .

# Establecer las variables de entorno
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# Exponer el puerto del backend
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["flask", "run", "--host=0.0.0.0"]