# Usa una imagen base ligera de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios desde la carpeta web
COPY ../../web/package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código fuente al contenedor desde la carpeta web
COPY ../../web .

# Expone el puerto 5173 para el frontend
EXPOSE 5173

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host"]