apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: avatares-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: avatarescr.azurecr.io/backend-devops:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: avatares-devops
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5173
  type: NodePort
