version: "3.8"
services:
  backend:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production

  frontend:
    build:
      context: ./web
    ports:
      - "5173:5173"
    environment:
      VITE_HOST: 0.0.0.0
      VITE_PORT: 5173
