name: CI/CD Avatares Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate project structure
      run: ls -R

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend-avatares:latest -f devops/docker/Dockerfile-Backend .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend-avatares:latest

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend-avatares:latest -f devops/docker/Dockerfile-Frontend .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend-avatares:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: avatares-devops/devops/terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: avatares-devops/devops/terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: avatares-devops/devops/terraform
      run: terraform apply -input=false tfplan
      env:
        ARM_ACCESS_TOKEN: ${{ secrets.AZURE_ACCESS_TOKEN }}
