name: CI/CD Avatares Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend-avatares:latest -f devops/docker/Dockerfile-Backend .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend-avatares:latest

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend-avatares:latest -f devops/docker/Dockerfile-Frontend .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend-avatares:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Init
      working-directory: devops/terraform
      run: terraform init

    - name: Terraform Import Service Plan
      working-directory: devops/terraform
      run: terraform import azurerm_service_plan.asp /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/AvataresResourcesGroup/providers/Microsoft.Web/serverfarms/AvataresAppServicePlan

    - name: Terraform Import Backend Web App
      working-directory: devops/terraform
      run: terraform import azurerm_linux_web_app.backend /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/AvataresResourcesGroup/providers/Microsoft.Web/sites/avatares-backend-service

    - name: Terraform Import Frontend Web App
      working-directory: devops/terraform
      run: terraform import azurerm_linux_web_app.frontend /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/AvataresResourcesGroup/providers/Microsoft.Web/sites/avatares-frontend-service

    - name: Terraform Plan
      working-directory: devops/terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: devops/terraform
      run: terraform apply -input=false tfplan